//*****************************************************************************
// pinmux.h
//
// function prototype for pinmuxconfig
//
// Copyright (C) 2014 Texas Instruments Incorporated - http://www.ti.com/
//
//*****************************************************************************
// This file was automatically generated by the CC31xx PinMux Utility
// Version: 1.0.2
//*****************************************************************************

#ifndef __PINMUX_H__
#define __PINMUX_H__

#include "hw_types.h"
#include "hw_memmap.h"
#include "hw_gpio.h"
#include "pin.h"
#include "rom.h"
#include "rom_map.h"
#include "rom_patch.h"
#include "gpio.h"
#include "prcm.h"

extern void PinMuxConfig(void);

#endif //  __PINMUX_H__
